---
avi_controller_k8s_storage_class:
  kind: StorageClass
  apiVersion: storage.k8s.io/v1
  metadata:
    name: "{{ avi_controller_storage_class_name }}"
  provisioner: kubernetes.io/gce-pd
  parameters:
    type: pd-ssd
    replication-type: regional-pd
  allowVolumeExpansion: true
  reclaimPolicy: Delete
  volumeBindingMode: WaitForFirstConsumer
