---
# tasks file for avinetworks.avicontroller_gke

- include_tasks: prerequisites.yml

# - name: Avi Controller | GKE | Suspend deplyoment | set replicas to 0
#   k8s_scale:
#     api_version: v1
#     kind: StatefulSet
#     name: node-0
#     namespace: "{{ avi_namespace }}"
#     replicas: 0
#     wait_timeout: 60

- name: Avi Controller | GKE | Suspend deplyoment | set replicas to 0
  command: kubectl scale -n {{ avi_namespace }} --replicas=0 statefulset/node-0
